server:
  port: 8082
spring:
  application:
    name: caicloud-consumer-movie
  zipkin:
    base-url: http://caicloud-zikpin:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://caicloud-discovery-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000