server:
  port: 8031
spring:
  application:
    name: caicloud-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://caicloud-discovery-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: caicloud-consumer-movie, caicloud-provider-user
  clusterNameExpression: "'default'"
